# 4.12.2023 V1.0.0 : CP900a5-33 publish BLOG as ZIP
# 10.12.2023 V1.0.1b : >> GIT RELEASE
# 12.12.2023 V1.0.2  : >> GIT RELEASE
# 13.12.2023 V1.1.0  : add MQTT
# 15.12.2023 V1.1.1  : CP900a6
# 19.12.2023 V1.1.2  : CP829 and add import mem report
# 21.12.2023 V1.2.3  : readout board and replace datetime lib with own time tools

DIAG=1  # __________________________________________ global print diagnostic on off
DIAGM=1 # __________________________________________ memory reporting

THIS_REVISION = "v1.1.3"
# THIS_OS = " CP829" # now read back from board
# __________________________________________________ LAN WIFI
WIFI_SSID = "kll-wlan_2.4G"
WIFI_PASSWORD = "WELOVEKOH-SAMUI"
WIFI_IP = "192.168.1.215" # ________________________ LOCAL WEB SERVER & 'data'
# __________________________________________________ LOCATION TIME ZONE
useNTP = 1 # _______________________________________ try NTP to RTC update
TZ_OFFSET = 7 # ____________________________________ LOCATION TIME ZONE

useMQTT=1 # ________________________________________ mqtt: enable
# __________________________________________________ local RPI4 as broker
MQTT_broker="192.168.1.104"
MQTT_port = 1883
MQTT_user = "uPICOW"
MQTT_pass = "pPICOW"
MQTT_TLS = "n" # ___________________________________ local mosquitto TLS no "n"

# __________________________________________________ TOPIC publish to RPI4:
MQTT_mtopic="PICOW"
MQTT_dtopic="PID/P215"


